/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/layout/Banner.vue')['default']
    Button: typeof import('primevue/button')['default']
    CallToAction: typeof import('./src/components/layout/CallToAction.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Chip: typeof import('primevue/chip')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    DescriptionList: typeof import('./src/components/layout/DescriptionList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hero: typeof import('./src/components/layout/Hero.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    PageHeading: typeof import('./src/components/layout/PageHeading.vue')['default']
    Pricing: typeof import('./src/components/layout/Pricing.vue')['default']
    SignIn: typeof import('./src/components/layout/SignIn.vue')['default']
    Stats: typeof import('./src/components/layout/Stats.vue')['default']
  }
}
